### PR TITLE
Don't increment non-saved entry (crashes live preview mode)

### PR DESCRIPTION
**Pull request by boboldehampsink**

### CODE REVIEW

**Comment by jordypixelcode** [comment]
Thanks @boboldehampsink 👍

**Comment by boboldehampsink** [comment]
Fast merge 👍  are you releasing a new version?

**Comment by jordypixelcode** [comment]
@boboldehampsink I've released the new version now, 1.0.2. Enjoy :-)

**Comment by boboldehampsink** [comment]
Thanks!

**Pull request merged**
